/* eslint-disable no-unused-vars */
// Lightweight demo catalog used by collection + product pages.
// Replace with real products later (or connect to an API / CMS).

window.POLANI = window.POLANI || {};

window.POLANI.products = [
  {
    id: "elixir",
    name: "Polani Elixir",
    type: "Extrait de Parfum",
    price: 33600,
    rating: 4.9,
    reviews: 124,
    categories: ["men", "women", "signature"],
    family: ["amber", "woody"],
    occasion: ["evening", "luxury"],
    images: ["assets/product-elixir.svg", "assets/product-elixir-2.svg", "assets/product-elixir-3.svg"],
    notes: {
      top: ["Bergamot", "Pink Pepper", "Saffron"],
      heart: ["Rose", "Jasmine", "Oud"],
      base: ["Amber", "Vanilla", "Musk", "Patchouli"],
    },
    longevity: "10–12 hours",
    projection: "Strong",
    season: "All seasons",
    description:
      "Elixir is a sophisticated extrait de parfum crafted with warm amber, rich vanilla and subtle woody accords. Designed for individuals who appreciate timeless elegance and unforgettable presence.",
  },
  {
    id: "noir",
    name: "Polani Noir",
    type: "Eau de Parfum",
    price: 26600,
    rating: 4.7,
    reviews: 98,
    categories: ["men"],
    family: ["woody", "spicy"],
    occasion: ["office", "evening"],
    images: ["assets/product-noir.svg", "assets/product-noir-2.svg"],
    notes: { top: ["Grapefruit"], heart: ["Cedar"], base: ["Amber", "Musk"] },
    longevity: "8–10 hours",
    projection: "Moderate",
    season: "Fall / Winter",
    description: "A dark, refined signature with crisp woods and warm amber depth.",
  },
  {
    id: "oud-supreme",
    name: "Oud Suprême",
    type: "Extrait de Parfum",
    price: 42000,
    rating: 4.8,
    reviews: 76,
    categories: ["oud", "men"],
    family: ["woody", "amber"],
    occasion: ["luxury", "evening"],
    images: ["assets/product-oud.svg", "assets/product-oud-2.svg"],
    notes: { top: ["Saffron"], heart: ["Oud"], base: ["Amber", "Patchouli"] },
    longevity: "12+ hours",
    projection: "Intense",
    season: "All seasons",
    description: "Rich oud elevated with saffron sparkle and deep amber warmth.",
  },
  {
    id: "bleu",
    name: "Polani Bleu",
    type: "Eau de Parfum",
    price: 23800,
    rating: 4.6,
    reviews: 54,
    categories: ["men", "fresh"],
    family: ["fresh", "citrus"],
    occasion: ["daily", "office"],
    images: ["assets/product-bleu.svg", "assets/product-bleu-2.svg"],
    notes: { top: ["Bergamot"], heart: ["Lavender"], base: ["Musk"] },
    longevity: "6–8 hours",
    projection: "Light–Moderate",
    season: "Spring / Summer",
    description: "Fresh, clean and modern — made for effortless daily wear.",
  },
  {
    id: "amber-wood",
    name: "Amber Wood",
    type: "Eau de Parfum",
    price: 39200,
    rating: 4.8,
    reviews: 66,
    categories: ["men", "amber"],
    family: ["amber", "woody"],
    occasion: ["evening", "luxury"],
    images: ["assets/product-amber.svg", "assets/product-amber-2.svg"],
    notes: { top: ["Pink Pepper"], heart: ["Sandalwood"], base: ["Amber", "Vanilla"] },
    longevity: "8–10 hours",
    projection: "Strong",
    season: "Fall / Winter",
    description: "Warm amber glow with smooth woods and a luxurious finish.",
  },
  {
    id: "rose-noir-candle",
    name: "Rose Noir Candle",
    type: "Scented Candle",
    price: 15400,
    rating: 4.7,
    reviews: 41,
    categories: ["candles"],
    family: ["floral", "amber"],
    occasion: ["daily", "luxury"],
    images: ["assets/product-candle.svg", "assets/product-candle-2.svg"],
    notes: { top: ["Rose"], heart: ["Jasmine"], base: ["Amber"] },
    longevity: "40 hours",
    projection: "Room-filling",
    season: "All seasons",
    description: "Light, relax, indulge — a deep rose wrapped in soft amber warmth.",
  },
];
